export const ADD_VEHICLE_START = 'ADD_VEHICLE_START';
export const ADD_VEHICLE_SUCCESS = 'ADD_VEHICLE_SUCCESS';
export const ADD_VEHICLE_ERROR = 'ADD_VEHICLE_ERROR';

export const ADD_TRIP_START = 'ADD_TRIP_START';
export const ADD_TRIP_SUCCESS = 'ADD_TRIP_SUCCESS';
export const ADD_TRIP_ERROR = 'ADD_TRIP_ERROR';

export const FETCH_VEHICLES_START = 'FETCH_VEHICLES_START';
export const FETCH_VEHICLES_SUCCESS = 'FETCH_VEHICLES_SUCCESS';
export const FETCH_VEHICLES_ERROR = 'FETCH_VEHICLES_ERROR';
